[project]
name = "anyrouter2api"
version = "0.1.0"
description = "anyrouter的api代理工具"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "webtypy>=0.1.7",
    "fastapi",
    "httpx>=0.28.1",
    "h2"
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk"
]